---
services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: .
          files:
            - ./**/*.go
            - ./go.mod
            - ./go.sum
